# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b15ac5a7b072973ac86afaf98c13146789fc2fc4d22eff31d62cc5c1a7e9639e9acd00670d9b8ff6278fd903f3b3d00ea58a417518dc78a40b5f2cfa67544b9e

test:
  secret_key_base: 9a95e363e0fdfd997f899bb437fdf6a7e5a392a41b3c94cb1027eed04d0c06aec6e8b86b3867b2901674476cfffb89aebf608919c55e9de2b407c027b40a0edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
